---
permalink: config-admin/anomaly-detection-monitoring-status.html 
sidebar: sidebar 
keywords:  
summary: Lo stato di monitoraggio del rilevamento delle anomalie è disponibile nelle query applicative, nei widget e nelle pagine delle risorse. 
---
= Stato di monitoraggio del rilevamento delle anomalie
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lo stato di monitoraggio del rilevamento delle anomalie è disponibile nelle query applicative, nei widget e nelle pagine delle risorse.



== Stato di monitoraggio del rilevamento delle anomalie

Per ciascuna applicazione, viene visualizzata una delle seguenti opzioni:

* *OK*
+
Non vengono rilevati problemi.

* *Formazione*
+
Il server di rilevamento delle anomalie sta caricando fino a 14 giorni di dati sulle prestazioni e li carica nel motore di rilevamento delle anomalie.

* *Supera il numero massimo di risorse*
+
È stato superato il numero massimo di risorse monitorate per un'applicazione. Non è possibile monitorare più di 4000 risorse per un'applicazione. Il monitoraggio viene messo in pausa fino a quando il numero di risorse non è inferiore o uguale a 4000. Ridurre il numero di risorse monitorate per continuare il monitoraggio.

* *Non riuscito*
+
La connessione al server di rilevamento delle anomalie non è riuscita.

* *Non monitorato*
+
Il monitoraggio dell'applicazione è disattivato. In query e widget, questo campo viene lasciato vuoto.


