---
permalink: config-admin/cdot-landing-page-terminology-storage-node.html 
sidebar: sidebar 
keywords:  
summary: Termini applicabili a oggetti o riferimenti che si possono trovare nelle landing page delle risorse dei nodi di storage NetApp Clustered Data ONTAP. 
---
= Nodo di storage Clustered Data ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Termini applicabili a oggetti o riferimenti che si possono trovare nelle landing page delle risorse dei nodi di storage NetApp Clustered Data ONTAP.



== Terminologia dei nodi di storage Clustered Data ONTAP

I seguenti termini si applicano agli oggetti o ai riferimenti presenti nelle landing page delle risorse del pool di storage NetApp Clustered Data ONTAP. Molti di questi termini si applicano anche ad altri data collezionisti.

* Storage -- a quale array di storage fa parte questo nodo. Obbligatorio.
* Partner HA -- sulle piattaforme in cui un nodo eseguirà il failover su un nodo e solo su un altro nodo, in genere viene visualizzato qui.
* Stato -- integrità del nodo. Disponibile solo quando l'array è abbastanza integro da essere inventorato da un'origine dati.
* Modello -- nome del modello del nodo.
* Version -- nome della versione del dispositivo.
* Serial number (numero di serie) - il numero di serie del nodo.
* Memoria -- memoria base 2, se disponibile.
* Utilizzo -- in ONTAP, si tratta di un indice di stress del controller da un algoritmo proprietario. Con ogni sondaggio sulle performance, viene riportato un numero compreso tra 0 e 100%, che è il più alto tra il conflitto del disco WAFL o l'utilizzo medio della CPU. Se si osservano valori sostenuti > 50%, ciò è indicativo di un sottodimensionamento -- potenzialmente un controller/nodo non sufficientemente grande o non abbastanza dischi rotanti per assorbire il carico di lavoro di scrittura.
* IOPS -- derivato direttamente dalle chiamate ONTAP ZAPI sull'oggetto nodo.
* Latenza -- derivata direttamente dalle chiamate ONTAP ZAPI sull'oggetto nodo.
* Throughput -- derivato direttamente dalle chiamate ONTAP ZAPI sull'oggetto nodo.
* Processori -- numero di CPU.

