---
permalink: config-admin/changing-oncommand-insight-internal-user-passwords.html 
sidebar: sidebar 
keywords:  
summary: 'Le policy di sicurezza potrebbero richiedere la modifica delle password nell"ambiente OnCommand Insight. Alcune delle password di un server si trovano su un server diverso dell"ambiente, che richiede la modifica della password su entrambi i server. Ad esempio, quando si modifica la password utente "inventario" su Insight Server, è necessario corrispondere alla password utente "inventario" sul connettore del server Data Warehouse configurato per quel server Insight.' 
---
= Modifica delle password utente interne di OnCommand Insight
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le policy di sicurezza potrebbero richiedere la modifica delle password nell'ambiente OnCommand Insight. Alcune delle password di un server si trovano su un server diverso dell'ambiente, che richiede la modifica della password su entrambi i server. Ad esempio, quando si modifica la password utente "`Inventory`" su Insight Server, è necessario corrispondere alla password utente "`Inventory`" sul connettore del server Data Warehouse configurato per Insight Server.



== Prima di iniziare

[NOTE]
====
Prima di modificare le password, è necessario comprendere le dipendenze degli account utente. Il mancato aggiornamento delle password su tutti i server richiesti causerà errori di comunicazione tra i componenti Insight.

====


== A proposito di questa attività

La seguente tabella elenca le password utente interne per Insight Server e i componenti Insight con password dipendenti che devono corrispondere alla nuova password.

|===


| Password di Insight Server | Modifiche richieste 


 a| 
_interno
 a| 



 a| 
acquisizione
 a| 
LAU, RAU



 a| 
dwh_internal
 a| 
Data Warehouse



 a| 
host
 a| 



 a| 
inventario
 a| 
Data Warehouse



 a| 
root
 a| 

|===
La seguente tabella elenca le password utente interne per Data Warehouse ed elenca i componenti Insight che hanno password dipendenti che devono corrispondere alla nuova password.

|===


| Password Data Warehouse | Modifiche richieste 


 a| 
cognos_admin
 a| 



 a| 
dwh
 a| 



 a| 
dwh_internal (modificato utilizzando l'interfaccia utente di configurazione di Server Connector)
 a| 
Server Insight



 a| 
dwhuser
 a| 



 a| 
host
 a| 



 a| 
Inventario (modificato utilizzando l'interfaccia utente di configurazione di Server Connector)
 a| 
Server Insight



 a| 
root
 a| 

|===
*Modifica delle password nell'interfaccia utente di configurazione della connessione del server DWH*

La seguente tabella elenca la password utente per LAU ed elenca i componenti Insight con password dipendenti che devono corrispondere alla nuova password.

|===


| LAU password | Modifiche richieste 


 a| 
acquisizione
 a| 
Insight Server, RAU

|===