---
permalink: config-admin/changing-user-passwords.html 
sidebar: sidebar 
keywords:  
summary: Un utente con privilegi di amministratore può modificare la password per qualsiasi account utente OnCommand Insight definito sul server locale. 
---
= Modifica delle password dell'utente
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un utente con privilegi di amministratore può modificare la password per qualsiasi account utente OnCommand Insight definito sul server locale.



== Prima di iniziare

Devono essere stati completati i seguenti elementi:

* Notifiche a chiunque acceda all'account utente che si sta modificando.
* Nuova password da utilizzare dopo questa modifica.




== A proposito di questa attività

Quando si utilizza questo metodo, non è possibile modificare la password di un utente validato tramite LDAP.



== Fasi

. Accedere con privilegi di amministratore.
. Nella barra degli strumenti Insight, fare clic su *Admin*.
. Fare clic su *Setup*.
. Fare clic sulla scheda *utenti*.
. Individuare la riga che visualizza l'account utente che si desidera modificare.
. A destra delle informazioni sull'utente, fare clic su *Edit user account* (Modifica account utente).
. Inserire la nuova *Password*, quindi immetterla di nuovo nel campo di verifica.
. Fare clic su *Save* (Salva).

