---
permalink: config-admin/configuring-anomaly-detection-for-applications.html 
sidebar: sidebar 
keywords:  
summary: 'È necessario attivare il rilevamento delle anomalie per monitorare l"infrastruttura di un"applicazione per rilevare eventuali comportamenti anomali. Il monitoraggio del rilevamento delle anomalie viene attivato o disattivato solo per le applicazioni.' 
---
= Configurazione delle applicazioni per il rilevamento delle anomalie
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario attivare il rilevamento delle anomalie per monitorare un comportamento anomalo dell'infrastruttura di un'applicazione. Il monitoraggio del rilevamento delle anomalie viene attivato o disattivato solo per le applicazioni.



== Prima di iniziare

* È necessario aver installato e configurato il motore di rilevamento delle anomalie.
* È necessario assegnare un'applicazione alla risorsa di calcolo (macchina virtuale o host) per qualsiasi risorsa per la quale si desidera ottenere informazioni di rilevamento delle anomalie. Insight rileva automaticamente il resto delle risorse.




== Fasi

. Accedere all'interfaccia utente Web di OnCommand Insightweb.
. Fare clic su *Manage* (Gestisci) e selezionare *Applications* (applicazioni).
. Individuare l'applicazione assegnata alla risorsa di calcolo.
. Nella sezione *anomalie*, assicurarsi che la casella di controllo *Monitor* nella parte superiore destra della sezione indichi *ON* anziché *OFF*; in caso contrario, fare clic in un punto qualsiasi della casella di controllo *Monitor* per attivare il controllo.
+
È possibile monitorare contemporaneamente fino a 48 applicazioni per rilevare eventuali anomalie.

+
Lo stato nella sezione visualizza "`Learning`" (apprendimento) per almeno un'ora; il motore di rilevamento delle anomalie esegue il precarica di un massimo di 14 giorni dei dati sulle prestazioni esistenti, in modo che il motore possa apprendere il comportamento del proprio ambiente. Dopo che il server Insight ha eseguito il primo polling delle risorse dell'ambiente, il motore di rilevamento delle anomalie calcola e restituisce un punteggio per l'applicazione entro tale periodo.



*Informazioni correlate*

link:assigning-applications-to-assets.md#["Assegnazione di applicazioni alle risorse"]
