---
permalink: config-admin/host-configuration-for-smart-card-and-certificate-login-dwh.html 
sidebar: sidebar 
keywords:  
summary: È necessario modificare la configurazione del data warehouse di OnCommand Insight per supportare gli accessi con smart card e certificati. 
---
= Configurazione di Data Warehouse per l'accesso a smart card e certificati
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
È necessario modificare la configurazione del data warehouse di OnCommand Insight per supportare gli accessi con smart card (CAC) e certificati.



== Prima di iniziare

* LDAP deve essere attivato nel sistema.
* LDAP `User principal account name` L'attributo deve corrispondere al campo LDAP che contiene il numero dell'ID governativo di un utente.
+
Il nome comune (CN) memorizzato nei CAC emessi dal governo è normalmente nel seguente formato: `first.last.ID`. Per alcuni campi LDAP, ad esempio `sAMAccountName`, questo formato è troppo lungo. Per questi campi, OnCommand Insight estrae solo il numero ID dal CNS.



[NOTE]
====
Per le istruzioni più aggiornate sul CAC e sul certificato, consulta i seguenti articoli della Knowledge base (è richiesto l'accesso al supporto):

* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_configure_Common_Access_Card_(CAC)_authentication_for_NetApp_OnCommand_Insight["Come configurare l'autenticazione della scheda di accesso comune (CAC) per OnCommand Insight"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_configure_Common_Access_Card_(CAC)_authentication_for_NetApp_OnCommand_Insight_DataWarehouse["Come configurare l'autenticazione della scheda di accesso comune (CAC) per il data warehouse OnCommand Insight"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_create_and_import_a_Certificate_Authority_(CA)_signed_certificate_into_OCI_and_DWH_7.3.X["Come creare e importare un certificato firmato dall'autorità di certificazione (CA) in OnComand Insight e OnCommand Insight Data Warehouse 7.3.x"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_create_a_Self_Signed_Certificate_within_OnCommand_Insight_7.3.X_installed_on_a_Windows_Host["Come creare un certificato autofirmato in OnCommand Insight 7.3.X installato su un host Windows"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_import_a_Cognos_Certificate_Authority_(CA)_signed_certificate_into_DWH_7.3.3_and_later["Come importare un certificato firmato dall'autorità di certificazione (CA) di Cognos in OnCommand DataWarehouse 7.3.3 e versioni successive"]


====


== Fasi

. Utilizzare regedit per modificare i valori del Registro di sistema in `HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Apache Software Foundation\Procrun2.0\SANscreen Server\Parameters\Java`
+
.. Modificare l'opzione JVM_Option `-DclientAuth=false` a. `-DclientAuth=true`.


+
Per Linux, modificare `clientAuth` parametro in `/opt/netapp/oci/scripts/wildfly.server`

. Aggiungere le autorità di certificazione (CA) al trustore del Data Warehouse:
+
.. In una finestra di comando, passare a. `..\SANscreen\wildfly\standalone\configuration`.
.. Utilizzare `keytool` Utility per elencare le CA attendibili: `C:\Program Files\SANscreen\java64\bin\keytool.exe -list -keystore server.trustore -storepass changeit`
+
La prima parola in ciascuna riga indica l'alias della CA.

.. Se necessario, fornire un file di certificato CA, di solito un `.pem` file. Per includere le CA del cliente con le CA attendibili del Data Warehouse, visitare il sito `..\SANscreen\wildfly\standalone\configuration` e utilizzare `keytool` comando di importazione: `C:\Program Files\SANscreen\java64\bin\keytool.exe -importcert -keystore server.trustore -alias my_alias -file 'path/to/my.pem' -v -trustcacerts`
+
My_alias è in genere un alias che identificherebbe facilmente la CA in``keytool -list`` operazione.



. Sul server OnCommand Insight, la `wildfly/standalone/configuration/standalone-full.xml` Il file deve essere modificato aggiornando verify-client su "REQUESTED" in ``/subsystem=undertow/server=default-server/https-listener=default-https``Per attivare CAC. Accedere al server Insight ed eseguire il comando appropriato:
+
|===


| SISTEMA OPERATIVO | Script 


 a| 
Windows
 a| 
<install dir>/SANscreen/wildfly/bin/enableCACforRemoteEJB.bat



 a| 
Linux
 a| 
/Opt/netapp/oci/wildfly/bin/enableCACforRemoteEJB.sh

|===
+
Dopo aver eseguito lo script, attendere il completamento del ricaricamento del server wildfly prima di passare al punto successivo.

. Riavviare il server OnCommand Insight.

