---
permalink: config-admin/managing-security-on-the-insight-server.html 
sidebar: sidebar 
keywords:  
summary: Il tool securityadmin consente di gestire le opzioni di sicurezza sul server Insight. La gestione della sicurezza include la modifica delle password, la generazione di nuove chiavi, il salvataggio e il ripristino delle configurazioni di sicurezza create o il ripristino delle configurazioni alle impostazioni predefinite. 
---
= Gestione della sicurezza sul server Insight
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `securityadmin` Consente di gestire le opzioni di sicurezza sul server Insight. La gestione della sicurezza include la modifica delle password, la generazione di nuove chiavi, il salvataggio e il ripristino delle configurazioni di sicurezza create o il ripristino delle configurazioni alle impostazioni predefinite.



== A proposito di questa attività

Si utilizza `securityadmin` tool per gestire la sicurezza:

* Finestre - `C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat`
* Linux - `/bin/oci-securityadmin.sh`




== Fasi

. Eseguire un accesso remoto al server Insight.
. Avviare lo strumento di amministrazione della protezione in modalità interattiva:
+
** Finestre - `C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat -i`
** Linux - `/bin/oci-securityadmin.sh -i`
+
Il sistema richiede le credenziali di accesso.



. Immettere il nome utente e la password di un account con credenziali "`Admin`".
. Selezionare *Server*.
+
Sono disponibili le seguenti opzioni di configurazione del server:

+
** *Backup*
+
Crea un file zip di backup del vault contenente tutte le password e le chiavi e colloca il file in una posizione specificata dall'utente o nelle seguenti posizioni predefinite:

+
*** Finestre - `C:\Program Files\SANscreen\backup\vault`
*** Linux - `/var/log/netapp/oci/backup/vault`


** *Ripristina*
+
Ripristina il backup zip del vault creato. Una volta ripristinato, tutte le password e le chiavi vengono ripristinate ai valori esistenti al momento della creazione del backup.

+
[NOTE]
====
Il ripristino può essere utilizzato per sincronizzare password e chiavi su più server, ad esempio: - Modificare la chiave di crittografia del server su un server - creare un backup del vault - ripristinare il backup del vault sul secondo server

====
** *Cambia chiave di crittografia*
+
Modificare la chiave di crittografia del server utilizzata per crittografare o decrittare le password utente proxy, le password utente SMTP, le password utente LDAP e così via.

+
[NOTE]
====
Quando si modificano le chiavi di crittografia, è necessario eseguire il backup della nuova configurazione di protezione in modo da poterla ripristinare dopo un aggiornamento o un'installazione.

====
** *Aggiorna password*
+
Modificare la password per gli account interni utilizzati da Insight. Vengono visualizzate le seguenti opzioni:

+
*** _interno
*** acquisizione
*** cognos_admin
*** dwh_internal
*** host
*** inventario
*** root






[NOTE]
====
Alcuni account devono essere sincronizzati quando si modificano le password. Ad esempio, se si modifica la password per l'utente di "acquisizione" sul server, è necessario modificare la password per l'utente di "acquisizione" su LAU, RAU e DWH in modo che corrisponda. Inoltre, quando si modificano le password, è necessario eseguire il backup della nuova configurazione di protezione in modo da poterla ripristinare dopo un aggiornamento o un'installazione.

====
* *Ripristina impostazioni predefinite*
+
Ripristina i valori predefiniti delle chiavi e delle password. I valori predefiniti sono quelli forniti durante l'installazione.

* *Esci*
+
Uscire da `securityadmin` tool.

+
.. Scegliere l'opzione che si desidera modificare e seguire le istruzioni.



