---
permalink: config-admin/managing-security-on-an-rau.html 
sidebar: sidebar 
keywords: rekey 
summary: Lo strumento securityadmin consente di gestire le opzioni di sicurezza su Raus. Potrebbe essere necessario eseguire il backup o il ripristino di una configurazione del vault, modificare le chiavi di crittografia o aggiornare le password per le unità di acquisizione. 
---
= Gestione della sicurezza su una RAU
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `securityadmin` Tool consente di gestire le opzioni di sicurezza su Raus. Potrebbe essere necessario eseguire il backup o il ripristino di una configurazione del vault, modificare le chiavi di crittografia o aggiornare le password per le unità di acquisizione.



== A proposito di questa attività

Si utilizza `securityadmin` tool per gestire la sicurezza:

* Finestre - `C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat`
* Linux - `/bin/oci-securityadmin.sh`


Uno scenario per aggiornare la configurazione di protezione per LAU/RAU è l'aggiornamento della password utente di 'acquisizione' quando la password per quell'utente è stata modificata sul server. LAU e tutti i Raus utilizzano la stessa password dell'utente 'acquisizione' del server per comunicare con il server.

L'utente di "acquisizione" esiste solo sul server Insight. RAU o LAU accedono come tale utente quando si connettono al server.

Per ulteriori informazioni, vedere le link:../config-admin\/security-management.html["Strumento securityadmin"]istruzioni.
