---
permalink: config-admin/managing-security-on-the-local-acquisition-unit.html 
sidebar: sidebar 
keywords:  
summary: 'Il tool securityadmin consente di gestire le opzioni di sicurezza sull"utente di acquisizione locale. La gestione della sicurezza include la gestione di chiavi e password, il salvataggio e il ripristino delle configurazioni di sicurezza create o il ripristino delle impostazioni predefinite delle configurazioni.' 
---
= Gestione della sicurezza sull'unità di acquisizione locale
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il `securityadmin` Tool consente di gestire le opzioni di sicurezza sull'utente di acquisizione locale (LAU). La gestione della sicurezza include la gestione di chiavi e password, il salvataggio e il ripristino delle configurazioni di sicurezza create o il ripristino delle impostazioni predefinite delle configurazioni.



== Prima di iniziare

Devi avere `admin` privilegi per eseguire attività di configurazione della sicurezza.



== A proposito di questa attività

Si utilizza `securityadmin` tool per gestire la sicurezza:

* Finestre - `C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat`
* Linux - `/bin/oci-securityadmin.sh`


Per ulteriori informazioni, vedere le link:../config-admin\/security-management.html["Strumento securityadmin"]istruzioni.
