---
permalink: faq/faq-additional-information.html 
sidebar: sidebar 
keywords: redhat,Linux 
summary: Dove posso trovare ulteriori informazioni? 
---
= Ulteriori informazioni
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dove posso ottenere informazioni aggiuntive finali per OnCommand Insight?



== Supporto dell'origine dati

Le informazioni sulle origini dati supportate da Insight sono disponibili nella matrice di supporto delle origini dati OnCommand Insight. Ti verrà richiesto di effettuare l'accesso utilizzando le credenziali del sito di supporto NetApp.

link:https://mysupport.netapp.com/api/content-service/staticcontents/content/products/oncommandinsight/DatasourceSupportMatrix_7.3.x.pdf["Matrice di supporto origine dati OnCommand Insight"]Matrice di supporto per le attuali versioni supportate di OnCommand Insight.



== Supporto

link:https://mysupport.netapp.com/matrix["Tool di matrice di interoperabilità NetApp (IMT)"]Descrive i dispositivi e le piattaforme supportati da OnCommand Insight.

link:https://mysupport.netapp.com/site/products/all/details/oncommand-insight/guideme-tab["Risoluzione guidata dei problemi di NetApp"]La risoluzione guidata dei problemi offre contenuti tecnici, risorse di istruzioni e procedure di risoluzione dei problemi organizzati in base a prodotti, funzionalità e attività. La chat consente di risolvere rapidamente i problemi senza aprire un caso o contattare il supporto tecnico.

NetApp Knowledgebase consente di accedere agli articoli tecnici per la gestione e l'amministrazione dei prodotti. Un piccolo sottoinsieme della knowledgebase è disponibile al pubblico. Un utente registrato ha accesso a una gamma più ampia di articoli della Knowledge base tecnica.

NetApp Global Services Contatti contattate il vostro centro di supporto regionale.



== Comunità

Storefront NetApp Scarica da un'ampia raccolta di modelli di report, pacchetti di soluzioni, data collector ed esempi di scripting NetApp per OnCommand Insight.

Video OnCommand Insight Guarda i video su una varietà di argomenti della nostra playlist video di prodotti OnCommand Insight.

Discussioni della community Insight Unisciti alla discussione su OnCommand Insight.



== Altro

Documentazione IBM Cognos per IBM Cognos sul web.
