---
settings:
  name: OnCommand Insight
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Documenti OnCommand Insight
    url: "/index.html"
  - section: relnotes
  - section: overview
  - section: install-linux
  - section: install-windows
  - section: config-admin
  - section: dwh
  - section: reporting
  - section: faq
  - section: howto
  - title: Note legali
    url: "/legal-notices.html"
