---
permalink: install-windows/upgrading-data-warehouse.html 
sidebar: sidebar 
keywords:  
summary: 'Dopo aver completato tutte le attività dei prerequisiti, è possibile accedere al server Data Warehouse ed eseguire il pacchetto di installazione per completare l"aggiornamento.' 
---
= Aggiornamento del data warehouse
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver completato tutte le attività dei prerequisiti, è possibile accedere al server Data Warehouse ed eseguire il pacchetto di installazione per completare l'aggiornamento.



== A proposito di questa attività

L'aggiornamento inline non è supportato dal Data Warehouse (DWH). Per eseguire l'aggiornamento alla nuova versione del software DWH, procedere come segue.

[NOTE]
====
Quando si aggiorna DWH, la cartella contenente il backup del vault dello strumento _securityadmin_ viene eliminata. Si consiglia vivamente di eseguire il backup del vault prima di aggiornare DWH. Per riferimento, le cartelle predefinite del vault sono le seguenti:

* Cartella del vault (vault in uso):``%SANSCREEN_HOME%\wildfly\standalone\configuration\vault``
* Backup del vault: `%SANSCREEN_HOME%\backup\vault`


Vedere http://ie-docs.rtp.openeng.netapp.com/oci-73_ram/topic/com.netapp.doc.oci-acg/GUID-E3351676-2088-4767-AAB5-CB1D8476291C.html?resultof=%22%76%61%75%6c%74%22%20["Gestione della sicurezza nel Data Warehouse"] per ulteriori informazioni.

====


== Fasi

. Accedere al server DWH utilizzando un account che dispone delle autorizzazioni di amministratore locale di Windows.
. Eseguire il backup di DWH DB e Reports utilizzando l'interfaccia del portale DWH.
. Eseguire il backup della configurazione di protezione se il server utilizza una configurazione di protezione non predefinita.
. Disinstallare il software DWH dal server.
. Riavviare il server per rimuovere i componenti dalla memoria.
. Installare la nuova versione di DWH sul server.
+
L'installazione richiede circa 2 ore. Si consiglia di lasciare selezionate tutte le impostazioni predefinite.

. Ripristinare la configurazione di sicurezza non predefinita sul server DWH.
. Ripristinare il database DWH sul server.




== Al termine

Dopo l'aggiornamento, è necessario ripristinare il database Data Warehouse, che può richiedere più tempo o meno dell'aggiornamento.

[NOTE]
====
Durante un aggiornamento di OnCommand Insight, non è raro che un cliente passi a un server Insight diverso. Se il server Insight è stato modificato, dopo il ripristino del database del data warehouse i connettori esistenti puntano all'indirizzo IP o al nome host del server precedente. Si consiglia di eliminare il connettore e crearne uno nuovo, per evitare possibili errori.

====