---
permalink: install-windows/upgrading-insight.html 
sidebar: sidebar 
keywords:  
summary: 'Dopo aver completato tutte le attività dei prerequisiti, accedere al server Insight ed eseguire il pacchetto di installazione per completare l"aggiornamento. Il processo di aggiornamento disinstalla il software esistente, installa il nuovo software e riavvia il server.' 
---
= Aggiornamento di Insight
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver completato tutte le attività dei prerequisiti, accedere al server Insight ed eseguire il pacchetto di installazione per completare l'aggiornamento. Il processo di aggiornamento disinstalla il software esistente, installa il nuovo software e riavvia il server.



== Prima di iniziare

Il pacchetto di installazione di Insight deve trovarsi sul server.

[NOTE]
====
*È necessario eseguire il backup del vault* prima di aggiornare OnCommand Insight.

Per ulteriori informazioni, vedere le link:../config-admin\/security-management.html["Strumento securityadmin"]istruzioni.

====


== Fasi

. Accedere al server Insight utilizzando un account che dispone delle autorizzazioni di amministratore locale di Windows.
. Individuare il pacchetto di installazione Insight (`SANscreenServer-x64-version_number-build_number.msi`) Utilizzando Esplora risorse e fare doppio clic su di esso.
+
Viene visualizzata la procedura guidata di installazione guidata di OnCommand.

. Spostare la finestra di avanzamento dal centro dello schermo e allontanarla dalla finestra dell'installazione guidata *Setup* in modo che gli errori generati non vengano nascosti.
. Seguire le istruzioni dell'installazione guidata.
+
Si consiglia di lasciare selezionate tutte le impostazioni predefinite.





== Al termine

Per verificare se l'aggiornamento è stato eseguito correttamente o se sono stati generati errori, controllare il log di aggiornamento nella seguente posizione: `<install directory>\SANscreen\wildfly\standalone\log`.
