---
permalink: install-windows/upgrading-data-warehouse.html 
sidebar: sidebar 
keywords:  
summary: 'Dopo aver completato tutte le attività dei prerequisiti, è possibile accedere al server Data Warehouse ed eseguire il pacchetto di installazione per completare l"aggiornamento.' 
---
= Aggiornamento del data warehouse
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver completato tutte le attività dei prerequisiti, è possibile accedere al server Data Warehouse ed eseguire il pacchetto di installazione per completare l'aggiornamento.



== A proposito di questa attività

L'aggiornamento inline non è supportato dal Data Warehouse (DWH). Per eseguire l'aggiornamento alla nuova versione del software DWH, procedere come segue.

[NOTE]
====
*È necessario eseguire il backup del vault* prima di aggiornare DWH.

Per ulteriori informazioni, vedere le link:../config-admin\/security-management.html["Strumento securityadmin"]istruzioni.

====


== Fasi

Quando si aggiorna il Data Warehouse, è necessario effettuare le seguenti operazioni:

. Dopo aver installato DWH 7,3.16, ripristinare il vault e il database nel seguente ordine:
+
.. Vault
.. Database


. Accedere al server DWH utilizzando un account che dispone delle autorizzazioni di amministratore locale di Windows.
. Eseguire il backup di DWH DB e Reports utilizzando l'interfaccia del portale DWH.
. Eseguire il backup del vault. Consultare la link:../config-admin/security-management.html["Securityadmin"] documentazione.
. Disinstallare il software DWH dal server.
. Riavviare il server per rimuovere i componenti dalla memoria.
. Installare la nuova versione di DWH sul server.
+
L'installazione richiede circa 2 ore. Si consiglia di lasciare selezionate tutte le impostazioni predefinite.

. Ripristinare il vault sul server DWH.
. Ripristinare il database DWH sul server.




== Al termine

Dopo l'aggiornamento, è necessario ripristinare il database Data Warehouse, che può richiedere più tempo o meno dell'aggiornamento.

[NOTE]
====
Durante un aggiornamento di OnCommand Insight, non è raro che un cliente passi a un server Insight diverso. Se il server Insight è stato modificato, dopo il ripristino del database del data warehouse i connettori esistenti puntano all'indirizzo IP o al nome host del server precedente. Si consiglia di eliminare il connettore e crearne uno nuovo, per evitare possibili errori.

====