---
permalink: install-linux/anomaly-detection-requirements.html 
sidebar: sidebar 
keywords: redhat 
summary: Il software di rilevamento delle anomalie richiede un sistema operativo specifico, quantità di memoria, core della CPU e spazio su disco. Per installare correttamente il software di rilevamento delle anomalie, è necessario rispettare determinati requisiti. 
---
= Requisiti di rilevamento delle anomalie
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il software di rilevamento delle anomalie richiede un sistema operativo specifico, quantità di memoria, core della CPU e spazio su disco. Per installare correttamente il software di rilevamento delle anomalie, è necessario rispettare determinati requisiti.

|===


| Componente | Obbligatorio 


 a| 
Sistema operativo
 a| 
Un computer che esegue una versione con licenza di uno dei seguenti sistemi, che non esegue altro software a livello di applicazione:

* Red Hat Enterprise Linux 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9, 8.1, 8.2, 8.3, 8.4, 8.5
* CentOS 7.5, 7.6, 7.7, 7.8, 7.9, Flusso CentOS 8
* Oracle Enterprise Linux 7.5, 7.6, 7.7, 7.8, 7.9, 8.1, 8.2, 8.3, 8.4, 8.5
* SUSE Enterprise Linux 15.1, 15.2, 15.3
* OpenSUSE 15.1, 15.2, 15.3


Una versione con licenza garantisce che le dipendenze richieste per l'installazione vengano risolte automaticamente dal sistema operativo.

Si consiglia di utilizzare un server dedicato.



 a| 
Macchina virtuale (VM)
 a| 
Il rilevamento delle anomalie può essere eseguito in un ambiente virtuale, a condizione che le risorse di CPU e memoria per l'istanza siano riservate.



 a| 
CPU e memoria
 a| 
Un 8 core. Server di memoria da 64 GB.



 a| 
Spazio su disco disponibile
 a| 
Il server richiede 200 GB di spazio libero su disco partizionato come segue:

* 150 GB `/var/lib`
* 25 GB `/var/log`
* 25 GB `/opt`


L'installazione del software richiede il seguente spazio su disco:

* 5 GB `/var/lib`
* 25 GB `/var/log`
* 25 GB `/opt`


Si tratta di una Best practice da montare ``/opt``e. su dischi separati dal file system root (`/`).



 a| 
Permessi
 a| 
Per installare il software di rilevamento delle anomalie sono necessarie le autorizzazioni sudo.



 a| 
Rete
 a| 
Il server Insight su cui si desidera installare il software di rilevamento delle anomalie deve risiedere nella stessa rete, o almeno nello stesso sito o data center, del server su cui è in esecuzione il motore di rilevamento delle anomalie. Il software di rilevamento delle anomalie non supporta la configurazione in una WAN (Wide-Area Network).

Le porte TCP 8080 e 9200 devono essere aperte sulla macchina virtuale.



 a| 
Prerequisiti
 a| 
È necessario disporre di una licenza Perform valida.è necessario disporre dell'indirizzo IP del server Insight su cui si desidera installare il software di rilevamento delle anomalie.

Se non si accetta la porta predefinita, è necessario disporre di un numero di porta alternativo sul server Insight.

Le porte TCP 8080 e 9200 devono essere aperte sulla macchina virtuale.

È necessario disporre di un nome utente e di una password per un account con privilegi di amministratore sulla macchina virtuale.

Immettere due barre rovesciate (società/utente) per un nome utente contenente una singola barra rovesciata (società/utente).

Un nome utente non può contenere una "`t`" dopo una barra rovesciata (società tom).

|===
[NOTE]
====
È necessario discutere e convalidare tutti i consigli di dimensionamento con un rappresentante NetApp.

====