---
permalink: install-linux/installing-oncommand-insight-data-warehouse-linux.html 
sidebar: sidebar 
keywords:  
summary: 'L"installazione è autonoma e include gli elementi necessari per eseguire e utilizzare il data warehouse OnCommand Insight.' 
---
= Installazione del data warehouse di OnCommand Insight
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'installazione è autonoma e include gli elementi necessari per eseguire e utilizzare il data warehouse di OnCommand Insight (DWH).



== Prima di iniziare

È necessario aver completato tutti i prerequisiti di installazione.



== A proposito di questa attività

Data Warehouse dispone di funzionalità di reporting di Cognos. Se si installa Insight su un server Linux, è tuttavia possibile utilizzare queste funzionalità solo se si installa Data Warehouse su un server Windows. Per informazioni sull'installazione del data warehouse su Windows e sulle funzionalità di reporting di Cognos, fare riferimento alla _Guida all'installazione di OnCommand Insight per Microsoft Windows_.



== Fasi

. Accedere al server Data Warehouse utilizzando un account con privilegi sudo.
. Accedere alla directory del server in cui si trovano i file di installazione e digitare il seguente comando:
+
`unzip oci-dwh-<version>-linux-x86_64.zip`

+
Verificare il numero di versione del file di installazione; il numero di versione potrebbe essere diverso da quello visualizzato nel comando.

. È possibile visualizzare la sintassi, gli argomenti dei comandi e l'utilizzo dei parametri per `oci-install.sh` prima di iniziare l'installazione:
+
`sudo ./oci-dwh-<version>-linux-x86_64/oci-install.sh --help`

. Eseguire lo script di installazione:
+
`sudo ./oci-dwh-<version>-linux-x86_64/oci-install.sh`

+
Quando si installa Insight Server o Data Warehouse su CentOS 9 Stream, Red Hat Enterprise Linux 9,4 o Oracle Linux 9,4, è necessario prima passare alla directory contenente il file dell'installatore e quindi eseguire il comando install utilizzando l'opzione della riga di comando "--install-mysql-dependencies":

+
....
cd /tmp/oci-7.3.16.1.297-linux-x86_64
sudo ./oci-install.sh --install-mysql-dependencies
....
. Leggere il Contratto di licenza, accettarlo e seguire le istruzioni.




== Risultati

Dopo aver risposto a tutte le richieste, l'installazione inizia e richiede circa 10 minuti, a seconda delle applicazioni installate.



== Sincronizza server e DWH


IMPORTANT: Dopo aver installato il Data Warehouse, è *necessario* sincronizzare il Data Warehouse con il server OnCommand Insight. Attenersi alla seguente procedura:

. Sul sistema del server OnCommand Insight, avviare lo strumento *securityadmin* in modalità interattiva
+
 securityadmin -i
. Modificare la password per gli utenti _inventory_ e _dwh_internal_ in password di propria scelta. *Prendere nota di queste password*, in quanto saranno necessarie di seguito.
. Riavviare il servizio DWH
. Su *ogni connettore* avvia lo strumento *securityadmin* in modalità interattiva. Saranno necessarie le password annotate al punto 2.
+
 securityadmin -i
. Modificare le password per gli utenti _inventory_ e _dwh_internal_ con le password utilizzate nel passaggio 2.
. Riavviare i servizi sui connettori.
. Aggiungere i connettori a DWH, utilizzando le password per gli utenti _inventory_ e _dwh_internal_ del passaggio 2

