---
permalink: install-linux/installing-an-ethernet-monitoring-unit-linux.html 
sidebar: sidebar 
keywords:  
summary: '"Le unità di monitoraggio Ethernet ispezionano i pacchetti di rete nel proprio ambiente, per consentire la risoluzione dei problemi relativi alle performance in termini di traffico di rete dagli host alle risorse di storage.' 
---
= Installazione di un'unità di monitoraggio Ethernet
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
"`le unità di monitoraggio Ethernet (EMU) ispezionano i pacchetti di rete nell'ambiente, per consentire la risoluzione dei problemi relativi alle prestazioni in termini di traffico di rete dagli host alle risorse di storage.



== Prima di iniziare

[NOTE]
====
L'unità di monitoraggio Ethernet (EMU) non è supportata in OnCommand Insight versione 7.3.12 e successive.

====
È necessario aver completato tutti i prerequisiti di installazione.



== Fasi

. Accedere al server EMU utilizzando un account con privilegi sudo.
. Accedere alla directory del server in cui si trovano i file di installazione e digitare il seguente comando:
+
`unzip oci-ethernet-<version>-linux-x86_64.zip`

+
Dove `<version>` è il numero di versione specificato nel nome file scaricato.

. È possibile visualizzare la sintassi, gli argomenti dei comandi e l'utilizzo dei parametri per `oci-install.sh`:
+
`sudo ./oci-ethernet-<version>-linux-x86_64/oci-install.sh --help`

. Eseguire lo script di installazione:
+
`sudo ./oci-ethernet-<version>-linux-x86_64/oci-install.sh`

. Leggere il Contratto di licenza e accettarlo.
. Rispondere a ciascuna richiesta:
+
** *OnCommand Insight* *Nome server o indirizzo IP* - Nome host o indirizzo IP per identificare il server OnCommand Insight. L'EMU utilizza questo nome/IP per aprire un collegamento di comunicazione con il server. Se si specifica un nome host, assicurarsi che sia possibile risolverlo tramite DNS.
** *Acquisition Unit Name* (Nome unità di acquisizione) - Nome univoco che identifica l'EMU.
** *Porta di acquisizione remota protetta OnCommand Insight (HTTPS)* - porta utilizzata dall'EMU per inviare le informazioni di modifica dell'ambiente al server OnCommand Insight. Questa impostazione deve corrispondere al valore immesso al momento dell'installazione del server OnCommand Insight e deve essere la stessa su tutte le EMU.
** *Ethernet PAS output directory* - inserire la cartella per l'output PAS.
** *Interfacce Ethernet PAS da monitorare* - immettere le interfacce di cui si desidera monitorare il traffico.
** *Enable jumbo packets* (attiva pacchetti jumbo) - se l'ambiente del cliente utilizza pacchetti jumbo, EMU crea buffer di pacchetti di grandi dimensioni per la lettura di tali pacchetti. In caso contrario, EMU utilizza il pool di memoria disponibile per i pacchetti Ethernet standard. Dopo aver risposto a tutte le richieste, l'installazione inizia e richiede circa 10 minuti, a seconda delle applicazioni installate.



