---
permalink: install-linux/uninstalling-data-warehouse.html 
sidebar: sidebar 
keywords:  
summary: Se necessario, è possibile disinstallare Data Warehouse. 
---
= Disinstallazione di Data Warehouse
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Se necessario, è possibile disinstallare Data Warehouse.



== Prima di iniziare

Eseguire il backup della versione corrente del database di data warehouse (DWH) di OnCommand Insight.



== A proposito di questa attività

La disinstallazione del data warehouse di OnCommand Insight elimina in modo permanente tutti i dati precedentemente raccolti.



== Fasi

. Accedere al server Data Warehouse utilizzando un account con privilegi sudo.
. Assicurarsi che tutte le finestre di OnCommand Insight siano chiuse.
. È possibile visualizzare la sintassi, gli argomenti dei comandi e l'utilizzo dei parametri per `uninstall.sh` immettendo il seguente comando: `sudo /usr/bin/oci-uninstall.sh --help`
. Digitare il seguente comando: `sudo /usr/bin/oci-uninstall.sh`

