---
permalink: install-linux/upgrading-the-anomaly-detection-engine.html 
sidebar: sidebar 
keywords:  
summary: 'A partire dalla versione 7.3.9 di OnCommand Insight è possibile eseguire un aggiornamento in linea del software di rilevamento delle anomalie. L"upgrade in-line preserva i dati di rilevamento delle anomalie e i punteggi delle anomalie.' 
---
= Aggiornamento del motore di rilevamento delle anomalie
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A partire dalla versione 7.3.9 di OnCommand Insight è possibile eseguire un aggiornamento in linea del software di rilevamento delle anomalie. L'upgrade in-line preserva i dati di rilevamento delle anomalie e i punteggi delle anomalie.



== Prima di iniziare

* Il sistema deve eseguire OnCommand Insight 7.3.7 o versione successiva.
* Si consiglia di aggiornare il server OnCommand Insight prima di aggiornare il motore di rilevamento delle anomalie.




== A proposito di questa attività

Per eseguire l'aggiornamento, attenersi alla seguente procedura:



== Fasi

. Accedere alla directory in cui si trova il programma di installazione: `cd oci-prelert-<version>-linux-x86_64`
. Installare il software di aggiornamento per il rilevamento delle anomalie: `sudo ./oci-prelert-install.sh`
+
Il software di rilevamento delle anomalie è stato registrato correttamente con il server OnCommand Insight.


