---
permalink: install-linux/upgrading-remote-acquisition-units.html 
sidebar: sidebar 
keywords:  
summary: Dopo aver aggiornato il software del server Insight, è necessario aggiornare il software di acquisizione remota. 
---
= Aggiornamento del software Remote Acquisition Unit
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver aggiornato il software del server Insight, è necessario aggiornare il software di acquisizione remota.

[NOTE]
====
Si consiglia vivamente di eseguire il backup del vault e del database prima di aggiornare DWH.

Vedere le link:../config-admin\/security-management.html["Strumento securityadmin"] istruzioni per ulteriori informazioni sul vault.

====


== Fasi

. Accedere al server RAU (Remote Acquisition Unit) utilizzando un account con privilegi sudo.
. Scarica il software Insight RAU dal sito di supporto di NetApp.
. Accedere alla directory di download e digitare il seguente comando:
+
`unzip oci-rau-<version>-linux-x86_64.zip`

+
Assicurarsi di disporre del numero di versione corretto del file di installazione.

. È possibile visualizzare la sintassi, gli argomenti dei comandi e l'utilizzo dei parametri per `oci-install.sh` :
+
`sudo ./oci-rau-<version>-linux-x86_64/oci-install.sh --help`

. Eseguire lo script di installazione:
+
`sudo ./oci-rau-<version>-linux-x86_64/oci-install.sh`

. Accettare il Contratto di licenza e seguire le istruzioni.

