---
permalink: install-linux/upgrading-data-warehouse.html 
sidebar: sidebar 
keywords:  
summary: Dopo aver aggiornato il software del server Insight, è necessario aggiornare il software del data warehouse. 
---
= Aggiornamento del software Data Warehouse
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dopo aver aggiornato il software del server Insight, è necessario aggiornare il software del data warehouse.



== Fasi

. Accedere al server Data Warehouse (DWH) utilizzando un account con privilegi sudo.
. Scarica il software Insight DWH dal sito di supporto di NetApp.
. Accedere alla directory di download e digitare il seguente comando:
+
`unzip oci-dwh-<version>-linux-x86_64.zip`

+
Assicurarsi di disporre del numero di versione corretto del file di installazione.

. È possibile visualizzare la sintassi, gli argomenti dei comandi e l'utilizzo dei parametri per `oci-install.sh` :
+
`sudo ./oci-dwh-<version>-linux-x86_64/oci-install.sh --help`

. Eseguire lo script di installazione:
+
`sudo ./oci-dwh-<version>-linux-x86_64/oci-install.sh`

. Accettare il Contratto di licenza e seguire le istruzioni.

