---
permalink: howto/configuring-servicenow-for-integration.html 
sidebar: sidebar 
keywords:  
summary: 'L"integrazione di ServiceNow con Insight richiede diverse attività di configurazione.' 
---
= Configurazione di ServiceNow per l'integrazione
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'integrazione di ServiceNow con Insight richiede diverse attività di configurazione.



== A proposito di questa attività

Quando si integra ServiceNow con Insight, è necessario eseguire le seguenti attività:

Sul lato ServiceNow:

* Elevare il ruolo
* Installare i set di aggiornamenti
* Configurare gli utenti


Dal punto di vista della Insight:

* Aggiungere l'utente ServiceNow


Sul lato del connettore Python:

* Installare Python
* Installare librerie aggiuntive
* Inizializzare il connettore
* Modificare il file config.ini
* Verificare il connettore
* Sincronizzare il connettore
* Pianificare l'esecuzione quotidiana delle attività


Ciascuno di questi elementi viene spiegato in maggiore dettaglio nelle sezioni seguenti.
