---
permalink: howto/preparation-and-prerequisites-for-servicenow-integration.html 
sidebar: sidebar 
keywords:  
summary: 'Prima dell"integrazione, è necessario soddisfare i requisiti e i prerequisiti necessari per ServiceNow, Insight e il connettore middleware Python.' 
---
= Preparazione e prerequisiti per l'integrazione di Service Now
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prima dell'integrazione, è necessario soddisfare i requisiti e i prerequisiti necessari per ServiceNow, Insight e il connettore middleware Python.



== Workflow consigliato

Quando si integra ServiceNow con Insight, si consiglia vivamente di utilizzare il seguente flusso di lavoro:

. Implementare prima il connettore middleware Python nell'istanza di sviluppo.
. Una volta che tutti i guasti sono stati identificati e corretti nell'istanza di sviluppo, implementare il connettore nell'istanza di test/fase.
. Una volta confermato il corretto funzionamento nell'istanza di staging, distribuire il connettore nell'istanza di produzione.


Se durante una di queste fasi vengono rilevati problemi, seguire la procedura di rollback e disattivare il connettore, quindi risolvere il problema e ridistribuire.



== Prerequisiti generali:

* Per ospitare il connettore middleware python, è possibile utilizzare un host standalone o una macchina virtuale (scelta consigliata) o l'host/macchina virtuale del server Insight.
* Si consiglia vivamente di eseguire il backup del server Insight di produzione e di implementarlo in un'istanza di sviluppo.
* ServiceNow deve rilevare con precisione i server nel CMDB.
* Insight deve essere in grado di rilevare con precisione i tuoi ambienti di storage e calcolo.
* Porta 443 e 80 per Insight Server e ServiceNow Instance.




== Prerequisiti di ServiceNow:

* Si consiglia vivamente di utilizzare un'istanza di sviluppo/test.
* Autorizzazione per caricare i set di aggiornamento ServiceNow.
* Permesso di creare utenti.
* ServiceNow versione Jakarta o successiva




== Prerequisiti di Insight:

* Si consiglia vivamente di utilizzare un'istanza di sviluppo/test.
* Autorizzazione alla creazione di utenti (autorizzazioni di amministratore).
* Insight versione 7.3.1 o successiva è supportato, ma per ottenere il massimo da Insight, utilizza la versione più recente.




== Prerequisiti del connettore middleware Python:

* Python versione 3.6 o superiore installato.
* Durante l'installazione di Python, selezionare la casella per abilitare tutti gli utenti. Questo imposta Python per le posizioni di installazione standard delle applicazioni.
* Durante l'installazione di Python, selezionare la casella per consentire al programma di installazione di aggiornare il percorso. In caso contrario, sarà necessario aggiornare il percorso manualmente.
* Scarica le librerie Python *pysnow* e *Requests*.

