---
sidebar: sidebar 
permalink: task_config_telegraf_consul.html 
keywords: telegraf, installation, install, consul 
summary: Configurazione del data collector console 
---
= Consul Data Collector
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Insights utilizza questo data collector per raccogliere le metriche da console.



== Installazione

. Da *osservabilità > Collector*, fare clic su *+Data Collector*. Scegliere Console.
+
Se non è stato configurato un agente per la raccolta, viene richiesto di link:task_config_telegraf_agent.html["installare un agente"] nel tuo ambiente.

+
Se si dispone di un agente già configurato, selezionare il sistema operativo o la piattaforma appropriati e fare clic su *continua*.

. Seguire le istruzioni nella schermata Consul Configuration (Configurazione console) per configurare il data collector. Le istruzioni variano a seconda del tipo di sistema operativo o piattaforma utilizzata per la raccolta dei dati.




== Setup (Configurazione)

Le informazioni sono disponibili in link:https://www.consul.io/docs/index.html["Documentazione di Consul"].



== Oggetti e contatori per console

Vengono raccolti i seguenti oggetti e i relativi contatori:

[cols="<.<,<.<,<.<,<.<"]
|===
| Oggetto: | Identificatori: | Attributi: | Punti dati: 


| Console | Namespace
Verificare l'ID
Nodo di servizio | IP nodo
Sistema operativo del nodo
UUID nodo
Nome del nodo
Nome servizio
Selezionare Nome
ID servizio
Stato | Critico
Passaggio
Attenzione 
|===


== Risoluzione dei problemi

Per ulteriori informazioni, consultare link:concept_requesting_support.html["Supporto"] pagina.
