---
sidebar: sidebar 
permalink: task_config_telegraf_kubernetes.html 
keywords: telegraf, installation, install, kubernetes 
summary: Configurazione del data collector Kubernetes 
---
= Kubernetes Data Collector
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Insights utilizza questo data collector per raccogliere le metriche di Kubernetes Pod, Node e Container.



== Installazione

Per istruzioni sull'installazione di Kubernetes, consultare la link:task_config_telegraf_agent.html#kubernetes["Installazione dell'agente"] pagina.


NOTE: Le informazioni relative alle *metriche di stato del kube* sono state spostate in link:task_config_telegraf_agent.html#kubernetes["Installazione dell'agente"] pagina.



== Oggetti e contatori

Vengono raccolti i seguenti oggetti e i relativi contatori:

[cols="<.<,<.<,<.<,<.<"]
|===
| Oggetto: | Identificatori: | Attributi: | Punti dati: 


| Container Kubernetes | Namespace
Pod
Container
Cluster | Nodo Kubernetes
Nome del nodo
Sistema operativo del nodo
UUID nodo
IP nodo | Nanosecondi CPU
Utilizzo della CPU Nanocores
Errori della pagina principale della memoria
Dimensione set residente memoria (RSS)
Set di lavoro memoria
Errori della pagina di memoria
Utilizzo della memoria
Filesystem root disponibile
Capacità di root filesystem
Filesystem root utilizzato 


| Nodo Kubernetes | Nodo Kubernetes
Cluster | Nome del nodo
Sistema operativo del nodo
UUID nodo
IP nodo | Utilizzo della CPU Nanocores
Nanosecondi di utilizzo della CPU
File system disponibile
File system totale
File system utilizzato
Memoria disponibile
Utilizzo della memoria
Errori della pagina principale della memoria
Errori della pagina di memoria
Dimensione set residente memoria (RSS)
Set di lavoro memoria
Errori rete RX (al secondo)
Byte Rx di rete (al secondo)
Errori TX di rete (al secondo)
Byte TX di rete (al secondo)
File system immagine runtime disponibile
Sistema di file immagine runtime utilizzato
Capacità del file system dell'immagine runtime 


| Pod Kubernetes | Namespace
Pod
Cluster | Nodo Kubernetes
Nome del nodo
IP nodo
Sistema operativo del nodo
UUID nodo | Byte TX di rete (al secondo)
Errori TX di rete (al secondo)
Byte Rx di rete (al secondo)
Errori rete RX (al secondo) 


| Volume del pod Kubernetes | Volume
Pod
Cluster
Namespace | Nodo Kubernetes
Nome del nodo
UUID nodo
IP nodo
Sistema operativo del nodo | Disponibile
Capacità
Utilizzato 


| Container di sistema Kubernetes | Contenitore del sistema
Nodo Kubernetes
Cluster | Nome del nodo
IP nodo
Sistema operativo del nodo
UUID nodo | Utilizzo della CPU Nanocores
Nanosecondi del core di utilizzo della CPU
Errori della pagina principale della memoria
Errori della pagina di memoria
Dimensione set residente memoria (RSS)
Utilizzo della memoria
Set di lavoro memoria
Filesystem root disponibile
Capacità di root filesystem
Log filesystem disponibile
Log capacità del filesystem 
|===


== Risoluzione dei problemi

[cols="2*"]
|===
| Problema: | Prova: 


| È stato eseguito il comando del programma di installazione di Kubernetes Agent, ma non viene visualizzato un pod agente Telegraf tramite:

 sudo kubectl --namespace ci-monitoring get pods | Controllare se si sono verificati errori durante la distribuzione di DaemonSet:

 sudo kubectl --namespace ci-monitoring descrivono ds telegraf-ds

Se sono presenti errori correlati a SecurityContextConstraints, procedere come segue:

1. Generare l'YAML di Telegraf DaemonSet

 sudo kubectl --namespace ci-monitoring get ds telegraf-ds -o yaml > /tmp/telegraf-ds.yaml

2. Arrestare il servizio Telegraf

 sudo kubectl --namespace ci-monitoring delete ds telegraf-ds

3. Creare la necessaria SecurityContextConstraint (vedere la sezione "Configurazione dell'agente per la raccolta dei dati")

4. Ricreare Telegraf DaemonSet 


| Ho configurato Telegraf per ottenere informazioni sul mio cluster Kubernetes, ma non vedo alcuna informazione in Cloud Insights. Nel file di log di Telegraf vengono visualizzati errori di "valore del campo di intestazione non valido" relativi al plug-in di input di kubernetes che ho configurato. | Assicurarsi che il file bearer_token di riferimento non abbia una nuova riga finale. Per verificarlo, eseguire il comando seguente e verificare che restituisca 0:

 coda -c1 <bearer_token_file> 
|===
Per ulteriori informazioni, consultare link:concept_requesting_support.html["Supporto"] pagina.
