---
sidebar: sidebar 
permalink: task_config_telegraf_node.html 
keywords: telegraf, installation, install, node, host 
summary: Configurazione del data collector Flink 
---
= Raccolta dati nodo
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Insights raccoglie le metriche dal nodo su cui si installa un agente.



== Installazione

. Da *osservabilità > Collector*, scegliere un sistema operativo/piattaforma. Si noti che l'installazione di qualsiasi data collector di integrazione (Kubernetes, Docker, Apache, ecc.) configurerà anche la raccolta di dati dei nodi.
. Seguire le istruzioni per configurare l'agente. Le istruzioni variano a seconda del tipo di sistema operativo o piattaforma utilizzata per la raccolta dei dati.




== Oggetti e contatori

I seguenti oggetti e i relativi contatori vengono raccolti come metriche del nodo:

[cols="<.<,<.<,<.<,<.<"]
|===
| Oggetto: | Identificatori: | Attributi: | Punti dati: 


| File system del nodo | UUID nodo
Dispositivo
Percorso
Tipo | IP nodo
Nome del nodo
Sistema operativo del nodo
Modalità | Gratuito
Inodes libero
Inodes totale
Inodes utilizzati
Totale
Totale utilizzato
Utilizzato 


| Disco del nodo | UUID nodo
Disco | IP nodo
Nome del nodo
Sistema operativo del nodo | Tempo io totale
IOPS in corso
Byte in lettura (al secondo)
Tempo di lettura totale
Letture (al secondo)
Totale tempo io ponderato
Byte di scrittura (al secondo)
Tempo di scrittura totale
Scritture (al sec)
Lunghezza coda disco corrente
Tempo di scrittura
Tempo di lettura
Io tempo 


| CPU del nodo | UUID nodo
CPU | IP nodo
Nome del nodo
Sistema operativo del nodo | Utilizzo della CPU del sistema
Utilizzo della CPU utente
Utilizzo CPU inattiva
Utilizzo della CPU del processore
Interrompi utilizzo CPU
Utilizzo della CPU DPC 


| Nodo | UUID nodo | IP nodo
Nome del nodo
Sistema operativo del nodo | Tempo di avvio del kernel
Switch di contesto kernel (per sec)
Kernel Entropy disponibile
Interrupt kernel (al secondo)
Processi kernel biforcati (per sec)
Memoria attiva
Memoria disponibile totale
Memoria disponibile
Memoria con buffer
Memoria cache
Limite di commit della memoria
Memoria impegnata come
Memoria sporca
Memoria libera
Memoria libera elevata
Totale memoria alta
Memoria dimensioni pagina enormi
Memoria pagine enormi libero
Memoria pagine enormi totale
Memoria in esaurimento
Totale memoria in esaurimento
Mappatura della memoria
Tabelle delle pagine di memoria
Memoria condivisa
Slab di memoria
Memoria di swap memorizzata nella cache
Scambio di memoria libero
Totale scambio memoria
Memoria totale
Memoria utilizzata totale
Memoria utilizzata
Blocco memoria Vmalloc
Memoria Vmalloc totale
Memoria Vmalloc utilizzata
Memoria cablata
Totale scrittura memoria
Tmp scrittura memoria
Errori della cache della memoria
Errori di azzeramento della richiesta di memoria
Errori della pagina di memoria
Pagine in memoria
Memoria non paginata
Paging memoria
Core cache di memoria
Memoria Standby cache normale
Riserva cache di standby della memoria
Errori di transizione della memoria
Processi bloccati
Processi morti
Processi inattivi
Elabora cercapersone
Processi in esecuzione
Processi in pausa
Processi interrotti
Totale processi
Elabora i thread totali
Processi sconosciuti
Processi Zombie
Lunghezza della coda del processore
Scambio libero
Totale swap
Totale swap utilizzato
Swap utilizzato
Sostituire
Sostituire
Tempo di attività del sistema
Numero di sistema CPU
Numero di utenti del sistema
Chiamate di sistema 


| Rete di nodi | Interfaccia di rete
UUID nodo | Nome del nodo
IP nodo
Sistema operativo del nodo | Byte ricevuti
Byte inviati
Pacchetti in uscita eliminati
Packets Outboud errors (pacchetti in uscita)
I pacchetti ricevuti sono scartati
Pacchetti ricevuti errori
Pacchetti ricevuti
Pacchetti inviati 
|===


== Setup (Configurazione)

Le informazioni relative all'installazione e alla risoluzione dei problemi sono disponibili sul link:task_config_telegraf_agent.html["Configurazione di un agente"] pagina.
